color0 #131316
color1 #ffb4ab
color2 #bbc3ff
color3 #c4c5dd
color4 #e6bad7
color5 #bbc3ff
color6 #c4c5dd
color7 #e4e1e6
color8 #90909a
color9 #ffb4ab
color10 #bbc3ff
color11 #c4c5dd
color12 #e6bad7
color13 #bbc3ff
color14 #c4c5dd
color15 #e4e1e6

cursor                #e4e1e6
cursor_text_color     #131316
background            #131316
foreground            #e4e1e6
selection_foreground  #c7c5d0
selection_background  #46464f
active_border_color   #bbc3ff
inactive_border_color #46464f
url_color             #bbc3ff
