-- Noctalia Color Palette and Group Configuration
-- Dynamically reads colors from noctalia-colors.conf which is auto-generated by the theme manager

-- HACKY SOLUTION BECAUSE NOCTALIA GENERATES COLORS ACCORDING TO OLD HYPRLAND CONFIG SYNTAX.

local function parse_colors(filepath)
    local colors = {
        -- Fallback defaults
        primary = "rgb(ffb596)",
        surface = "rgb(181210)",
        secondary = "rgb(e6bead)",
        error = "rgb(ffb4ab)",
        tertiary = "rgb(d2c78f)",
        surface_lowest = "rgb(120d0b)",
    }
    
    local file = io.open(filepath, "r")
    if not file then
        return colors
    end
    
    for line in file:lines() do
        -- Match lines like: $primary = rgb(ffb596)
        local varname, value = line:match("^%$(%w+)%s*=%s*rgb%(([^)]+)%)")
        if varname and value then
            colors[varname] = "rgb(" .. value .. ")"
        end
    end
    
    file:close()
    return colors
end

-- Load colors from the dynamically-generated noctalia-colors.conf
local config_path = os.getenv("HOME") .. "/.config/hypr/noctalia/noctalia-colors.conf"
local colors = parse_colors(config_path)

-- Apply colors to general configuration
hl.config({
    general = {
        col = {
            active_border = colors.primary,
            inactive_border = colors.surface,
        },
    },
})

-- Group color configuration
hl.config({
    group = {
        col = {
            border_active = colors.secondary,
            border_inactive = colors.surface,
            border_locked_active = colors.error,
            border_locked_inactive = colors.surface,
        },
        groupbar = {
            col = {
                active = colors.secondary,
                inactive = colors.surface,
                locked_active = colors.error,
                locked_inactive = colors.surface,
            },
        },
    },
})

return colors
