format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$line_break\
$character"""

[directory]
read_only = " "
truncation_symbol = '…/'

[git_branch]
format = "[$symbol$branch]($style) "
style = "bright-black"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'
style = "bright-black"
ahead = "[⇡$count](purple)"
behind = "[⇣$count](red)"
diverged = "⇡$ahead_count⇣$behind_count"
staged = "[+$count](green)"
modified = "[!$count](yellow)"
untracked = "[?$count](blue)"
stashed = ""

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"